package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlElectric<M extends BaseXlElectric<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setCalctype(java.lang.String calctype) {
		set("calctype", calctype);
	}
	
	public java.lang.String getCalctype() {
		return getStr("calctype");
	}

	public void setDay(java.lang.String day) {
		set("day", day);
	}
	
	public java.lang.String getDay() {
		return getStr("day");
	}

}
