package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlAidDid<M extends BaseXlAidDid<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAid(java.lang.Integer aid) {
		set("aid", aid);
	}
	
	public java.lang.Integer getAid() {
		return getInt("aid");
	}

	public void setDid(java.lang.Integer did) {
		set("did", did);
	}
	
	public java.lang.Integer getDid() {
		return getInt("did");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setGid(java.lang.Integer gid) {
		set("gid", gid);
	}
	
	public java.lang.Integer getGid() {
		return getInt("gid");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
