package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlAnalogdoc<M extends BaseXlAnalogdoc<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAid(java.lang.String aid) {
		set("aid", aid);
	}
	
	public java.lang.String getAid() {
		return getStr("aid");
	}

	public void setAname(java.lang.String aname) {
		set("aname", aname);
	}
	
	public java.lang.String getAname() {
		return getStr("aname");
	}

	public void setDataunit(java.lang.String dataunit) {
		set("dataunit", dataunit);
	}
	
	public java.lang.String getDataunit() {
		return getStr("dataunit");
	}

	public void setDataperiod(java.lang.String dataperiod) {
		set("dataperiod", dataperiod);
	}
	
	public java.lang.String getDataperiod() {
		return getStr("dataperiod");
	}

	public void setRatio(java.lang.String ratio) {
		set("ratio", ratio);
	}
	
	public java.lang.String getRatio() {
		return getStr("ratio");
	}

	public void setCaltypeid(java.lang.String caltypeid) {
		set("caltypeid", caltypeid);
	}
	
	public java.lang.String getCaltypeid() {
		return getStr("caltypeid");
	}

	public void setInitvalue(java.lang.String initvalue) {
		set("initvalue", initvalue);
	}
	
	public java.lang.String getInitvalue() {
		return getStr("initvalue");
	}

	public void setRangestart(java.lang.String rangestart) {
		set("rangestart", rangestart);
	}
	
	public java.lang.String getRangestart() {
		return getStr("rangestart");
	}

	public void setRangeend(java.lang.String rangeend) {
		set("rangeend", rangeend);
	}
	
	public java.lang.String getRangeend() {
		return getStr("rangeend");
	}

	public void setJabnormal(java.lang.String jabnormal) {
		set("jabnormal", jabnormal);
	}
	
	public java.lang.String getJabnormal() {
		return getStr("jabnormal");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setDid(java.lang.String did) {
		set("did", did);
	}
	
	public java.lang.String getDid() {
		return getStr("did");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

}
