package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlZhztWarter<M extends BaseXlZhztWarter<M>> extends Model<M> implements IBean {

	public void setCounterId(java.lang.String counterId) {
		set("counterId", counterId);
	}
	
	public java.lang.String getCounterId() {
		return getStr("counterId");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public void setNum(java.lang.String num) {
		set("num", num);
	}
	
	public java.lang.String getNum() {
		return getStr("num");
	}

	public void setAccountNo(java.lang.String accountNo) {
		set("account_no", accountNo);
	}
	
	public java.lang.String getAccountNo() {
		return getStr("account_no");
	}

	public void setDate(java.lang.String date) {
		set("date", date);
	}
	
	public java.lang.String getDate() {
		return getStr("date");
	}

}
