package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCthyDevicesInfo<M extends BaseCthyDevicesInfo<M>> extends Model<M> implements IBean {

	public void setDeviceNo(java.lang.String deviceNo) {
		set("deviceNo", deviceNo);
	}
	
	public java.lang.String getDeviceNo() {
		return getStr("deviceNo");
	}

	public void setCardNo(java.lang.String cardNo) {
		set("cardNo", cardNo);
	}
	
	public java.lang.String getCardNo() {
		return getStr("cardNo");
	}

	public void setTotalMoveAmount(java.lang.String totalMoveAmount) {
		set("totalMoveAmount", totalMoveAmount);
	}
	
	public java.lang.String getTotalMoveAmount() {
		return getStr("totalMoveAmount");
	}

	public void setLeaveAmount(java.lang.String leaveAmount) {
		set("leaveAmount", leaveAmount);
	}
	
	public java.lang.String getLeaveAmount() {
		return getStr("leaveAmount");
	}

	public void setWarnAmount(java.lang.String warnAmount) {
		set("warnAmount", warnAmount);
	}
	
	public java.lang.String getWarnAmount() {
		return getStr("warnAmount");
	}

	public void setVoltage(java.lang.String voltage) {
		set("voltage", voltage);
	}
	
	public java.lang.String getVoltage() {
		return getStr("voltage");
	}

	public void setDbm(java.lang.String dbm) {
		set("dbm", dbm);
	}
	
	public java.lang.String getDbm() {
		return getStr("dbm");
	}

	public void setSumWorkTime(java.lang.String sumWorkTime) {
		set("sumWorkTime", sumWorkTime);
	}
	
	public java.lang.String getSumWorkTime() {
		return getStr("sumWorkTime");
	}

	public void setLimitAmount(java.lang.String limitAmount) {
		set("limitAmount", limitAmount);
	}
	
	public java.lang.String getLimitAmount() {
		return getStr("limitAmount");
	}

	public void setMeterDateTime(java.lang.String meterDateTime) {
		set("meterDateTime", meterDateTime);
	}
	
	public java.lang.String getMeterDateTime() {
		return getStr("meterDateTime");
	}

	public void setValueStatus(java.lang.String valueStatus) {
		set("valueStatus", valueStatus);
	}
	
	public java.lang.String getValueStatus() {
		return getStr("valueStatus");
	}

	public void setBatteryStatus(java.lang.String batteryStatus) {
		set("batteryStatus", batteryStatus);
	}
	
	public java.lang.String getBatteryStatus() {
		return getStr("batteryStatus");
	}

	public void setMagneticStatus(java.lang.String magneticStatus) {
		set("magneticStatus", magneticStatus);
	}
	
	public java.lang.String getMagneticStatus() {
		return getStr("magneticStatus");
	}

	public void setReturnCode(java.lang.String returnCode) {
		set("returnCode", returnCode);
	}
	
	public java.lang.String getReturnCode() {
		return getStr("returnCode");
	}

	public void setReturnMsg(java.lang.String returnMsg) {
		set("returnMsg", returnMsg);
	}
	
	public java.lang.String getReturnMsg() {
		return getStr("returnMsg");
	}

	public void setCommand(java.lang.String command) {
		set("command", command);
	}
	
	public java.lang.String getCommand() {
		return getStr("command");
	}

	public void setCommandStatus(java.lang.String commandStatus) {
		set("commandStatus", commandStatus);
	}
	
	public java.lang.String getCommandStatus() {
		return getStr("commandStatus");
	}

	public void setCustomerNo(java.lang.String customerNo) {
		set("customerNo", customerNo);
	}
	
	public java.lang.String getCustomerNo() {
		return getStr("customerNo");
	}

	public void setCustomerPsd(java.lang.String customerPsd) {
		set("customerPsd", customerPsd);
	}
	
	public java.lang.String getCustomerPsd() {
		return getStr("customerPsd");
	}

	public void setDateTime1(java.lang.String dateTime1) {
		set("dateTime1", dateTime1);
	}
	
	public java.lang.String getDateTime1() {
		return getStr("dateTime1");
	}

	public void setDateTime2(java.lang.String dateTime2) {
		set("dateTime2", dateTime2);
	}
	
	public java.lang.String getDateTime2() {
		return getStr("dateTime2");
	}

	public void setDateTime3(java.lang.String dateTime3) {
		set("dateTime3", dateTime3);
	}
	
	public java.lang.String getDateTime3() {
		return getStr("dateTime3");
	}

	public void setDateTime4(java.lang.String dateTime4) {
		set("dateTime4", dateTime4);
	}
	
	public java.lang.String getDateTime4() {
		return getStr("dateTime4");
	}

	public void setDeviceType(java.lang.String deviceType) {
		set("deviceType", deviceType);
	}
	
	public java.lang.String getDeviceType() {
		return getStr("deviceType");
	}

	public void setForceStatus(java.lang.String forceStatus) {
		set("forceStatus", forceStatus);
	}
	
	public java.lang.String getForceStatus() {
		return getStr("forceStatus");
	}

	public void setHistoryData(java.lang.String historyData) {
		set("historyData", historyData);
	}
	
	public java.lang.String getHistoryData() {
		return getStr("historyData");
	}

	public void setInitialValue(java.lang.String initialValue) {
		set("initialValue", initialValue);
	}
	
	public java.lang.String getInitialValue() {
		return getStr("initialValue");
	}

	public void setLastDateTime(java.lang.String lastDateTime) {
		set("lastDateTime", lastDateTime);
	}
	
	public java.lang.String getLastDateTime() {
		return getStr("lastDateTime");
	}

}
