package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlGroupanalog<M extends BaseXlGroupanalog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAnalogname(java.lang.String analogname) {
		set("analogname", analogname);
	}
	
	public java.lang.String getAnalogname() {
		return getStr("analogname");
	}

	public void setAnalogid(java.lang.String analogid) {
		set("analogid", analogid);
	}
	
	public java.lang.String getAnalogid() {
		return getStr("analogid");
	}

	public void setSym(java.lang.String sym) {
		set("sym", sym);
	}
	
	public java.lang.String getSym() {
		return getStr("sym");
	}

	public void setCoe(java.lang.String coe) {
		set("coe", coe);
	}
	
	public java.lang.String getCoe() {
		return getStr("coe");
	}

	public void setSdt(java.lang.String sdt) {
		set("sdt", sdt);
	}
	
	public java.lang.String getSdt() {
		return getStr("sdt");
	}

	public void setEdt(java.lang.String edt) {
		set("edt", edt);
	}
	
	public java.lang.String getEdt() {
		return getStr("edt");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setGroupid(java.lang.String groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.String getGroupid() {
		return getStr("groupid");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

}
