package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmsTaskconfig<M extends BaseEmsTaskconfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer Id) {
		set("Id", Id);
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public void setName(java.lang.String Name) {
		set("Name", Name);
	}
	
	public java.lang.String getName() {
		return getStr("Name");
	}

	public void setType(java.lang.Integer Type) {
		set("Type", Type);
	}
	
	public java.lang.Integer getType() {
		return getInt("Type");
	}

	public void setExecuteType(java.lang.Integer ExecuteType) {
		set("ExecuteType", ExecuteType);
	}
	
	public java.lang.Integer getExecuteType() {
		return getInt("ExecuteType");
	}

	public void setPeriod(java.lang.Integer Period) {
		set("Period", Period);
	}
	
	public java.lang.Integer getPeriod() {
		return getInt("Period");
	}

	public void setExecuteYear(java.lang.Integer ExecuteYear) {
		set("ExecuteYear", ExecuteYear);
	}
	
	public java.lang.Integer getExecuteYear() {
		return getInt("ExecuteYear");
	}

	public void setExecuteMonth(java.lang.Integer ExecuteMonth) {
		set("ExecuteMonth", ExecuteMonth);
	}
	
	public java.lang.Integer getExecuteMonth() {
		return getInt("ExecuteMonth");
	}

	public void setExecuteWeek(java.lang.Integer ExecuteWeek) {
		set("ExecuteWeek", ExecuteWeek);
	}
	
	public java.lang.Integer getExecuteWeek() {
		return getInt("ExecuteWeek");
	}

	public void setExecuteDay(java.lang.Integer ExecuteDay) {
		set("ExecuteDay", ExecuteDay);
	}
	
	public java.lang.Integer getExecuteDay() {
		return getInt("ExecuteDay");
	}

	public void setExecuteHour(java.lang.Integer ExecuteHour) {
		set("ExecuteHour", ExecuteHour);
	}
	
	public java.lang.Integer getExecuteHour() {
		return getInt("ExecuteHour");
	}

	public void setExecuteMinute(java.lang.Integer ExecuteMinute) {
		set("ExecuteMinute", ExecuteMinute);
	}
	
	public java.lang.Integer getExecuteMinute() {
		return getInt("ExecuteMinute");
	}

	public void setExecuteSecond(java.lang.Integer ExecuteSecond) {
		set("ExecuteSecond", ExecuteSecond);
	}
	
	public java.lang.Integer getExecuteSecond() {
		return getInt("ExecuteSecond");
	}

	public void setState(java.lang.Integer State) {
		set("State", State);
	}
	
	public java.lang.Integer getState() {
		return getInt("State");
	}

}
