package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlUnitcalcgroup<M extends BaseXlUnitcalcgroup<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return getStr("uname");
	}

	public void setIoo(java.lang.String ioo) {
		set("ioo", ioo);
	}
	
	public java.lang.String getIoo() {
		return getStr("ioo");
	}

	public void setGroupname(java.lang.String groupname) {
		set("groupname", groupname);
	}
	
	public java.lang.String getGroupname() {
		return getStr("groupname");
	}

	public void setGroupid(java.lang.String groupid) {
		set("groupid", groupid);
	}
	
	public java.lang.String getGroupid() {
		return getStr("groupid");
	}

	public void setDataid(java.lang.String dataid) {
		set("dataid", dataid);
	}
	
	public java.lang.String getDataid() {
		return getStr("dataid");
	}

	public void setDataname(java.lang.String dataname) {
		set("dataname", dataname);
	}
	
	public java.lang.String getDataname() {
		return getStr("dataname");
	}

	public void setDatacode(java.lang.String datacode) {
		set("datacode", datacode);
	}
	
	public java.lang.String getDatacode() {
		return getStr("datacode");
	}

	public void setDuname(java.lang.String duname) {
		set("duname", duname);
	}
	
	public java.lang.String getDuname() {
		return getStr("duname");
	}

	public void setDucode(java.lang.String ducode) {
		set("ducode", ducode);
	}
	
	public java.lang.String getDucode() {
		return getStr("ducode");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
