package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlAnalogTransfer<M extends BaseXlAnalogTransfer<M>> extends Model<M> implements IBean {

	public void setAnalogid(java.lang.String analogid) {
		set("analogid", analogid);
	}
	
	public java.lang.String getAnalogid() {
		return getStr("analogid");
	}

	public void setDatavalue(java.lang.String datavalue) {
		set("datavalue", datavalue);
	}
	
	public java.lang.String getDatavalue() {
		return getStr("datavalue");
	}

	public void setDatetime(java.lang.String datetime) {
		set("datetime", datetime);
	}
	
	public java.lang.String getDatetime() {
		return getStr("datetime");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

}
