package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWarterMeterInput<M extends BaseWarterMeterInput<M>> extends Model<M> implements IBean {

	public void setDid(java.lang.String did) {
		set("did", did);
	}
	
	public java.lang.String getDid() {
		return getStr("did");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}
	
	public java.lang.String getDeviceId() {
		return getStr("device_id");
	}

	public void setWaterMeterName(java.lang.String waterMeterName) {
		set("water_meter_name", waterMeterName);
	}
	
	public java.lang.String getWaterMeterName() {
		return getStr("water_meter_name");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setIo(java.lang.String io) {
		set("io", io);
	}
	
	public java.lang.String getIo() {
		return getStr("io");
	}

	public void setPname(java.lang.String pname) {
		set("pname", pname);
	}
	
	public java.lang.String getPname() {
		return getStr("pname");
	}

}
