package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEerBase<M extends BaseEerBase<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setDt(java.lang.String dt) {
		set("dt", dt);
	}
	
	public java.lang.String getDt() {
		return getStr("dt");
	}

	public void setCapacity(java.lang.Float capacity) {
		set("capacity", capacity);
	}
	
	public java.lang.Float getCapacity() {
		return getFloat("capacity");
	}

	public void setConsumption(java.lang.Float consumption) {
		set("consumption", consumption);
	}
	
	public java.lang.Float getConsumption() {
		return getFloat("consumption");
	}

	public void setSingleconsumption(java.lang.String singleconsumption) {
		set("singleconsumption", singleconsumption);
	}
	
	public java.lang.String getSingleconsumption() {
		return getStr("singleconsumption");
	}

	public void setDtype(java.lang.Integer dtype) {
		set("dtype", dtype);
	}
	
	public java.lang.Integer getDtype() {
		return getInt("dtype");
	}

	public void setAdddate(java.util.Date adddate) {
		set("adddate", adddate);
	}
	
	public java.util.Date getAdddate() {
		return get("adddate");
	}

}
