package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEerUnit<M extends BaseEerUnit<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setUnitname(java.lang.String unitname) {
		set("unitname", unitname);
	}
	
	public java.lang.String getUnitname() {
		return getStr("unitname");
	}

	public void setDtype(java.lang.String dtype) {
		set("dtype", dtype);
	}
	
	public java.lang.String getDtype() {
		return getStr("dtype");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

}
