package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlDatacode<M extends BaseXlDatacode<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDataid(java.lang.Integer dataid) {
		set("dataid", dataid);
	}
	
	public java.lang.Integer getDataid() {
		return getInt("dataid");
	}

	public void setDataname(java.lang.String dataname) {
		set("dataname", dataname);
	}
	
	public java.lang.String getDataname() {
		return getStr("dataname");
	}

	public void setDatacode(java.lang.String datacode) {
		set("datacode", datacode);
	}
	
	public java.lang.String getDatacode() {
		return getStr("datacode");
	}

	public void setPdataid(java.lang.Integer pdataid) {
		set("pdataid", pdataid);
	}
	
	public java.lang.Integer getPdataid() {
		return getInt("pdataid");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setIo(java.lang.Integer io) {
		set("io", io);
	}
	
	public java.lang.Integer getIo() {
		return getInt("io");
	}

}
