package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlDaydataE<M extends BaseXlDaydataE<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.String uid) {
		set("uid", uid);
	}
	
	public java.lang.String getUid() {
		return getStr("uid");
	}

	public void setDt(java.lang.String dt) {
		set("dt", dt);
	}
	
	public java.lang.String getDt() {
		return getStr("dt");
	}

	public void setIo(java.lang.String io) {
		set("io", io);
	}
	
	public java.lang.String getIo() {
		return getStr("io");
	}

	public void setEfc(java.lang.String efc) {
		set("efc", efc);
	}
	
	public java.lang.String getEfc() {
		return getStr("efc");
	}

	public void setTo(java.lang.String to) {
		set("to", to);
	}
	
	public java.lang.String getTo() {
		return getStr("to");
	}

	public void setPi(java.lang.String pi) {
		set("pi", pi);
	}
	
	public java.lang.String getPi() {
		return getStr("pi");
	}

	public void setPe(java.lang.String pe) {
		set("pe", pe);
	}
	
	public java.lang.String getPe() {
		return getStr("pe");
	}

	public void setSdt(java.lang.String sdt) {
		set("sdt", sdt);
	}
	
	public java.lang.String getSdt() {
		return getStr("sdt");
	}

	public void setEdt(java.lang.String edt) {
		set("edt", edt);
	}
	
	public java.lang.String getEdt() {
		return getStr("edt");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setFl(java.lang.String fl) {
		set("fl", fl);
	}
	
	public java.lang.String getFl() {
		return getStr("fl");
	}

	public void setVa(java.lang.String va) {
		set("va", va);
	}
	
	public java.lang.String getVa() {
		return getStr("va");
	}

}
