package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmsElecgasGroup<M extends BaseEmsElecgasGroup<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setUID(java.lang.String UID) {
		set("UID", UID);
	}
	
	public java.lang.String getUID() {
		return getStr("UID");
	}

	public void setGroupName(java.lang.String groupName) {
		set("GROUP_NAME", groupName);
	}
	
	public java.lang.String getGroupName() {
		return getStr("GROUP_NAME");
	}

	public void setElecId(java.lang.String elecId) {
		set("ELEC_ID", elecId);
	}
	
	public java.lang.String getElecId() {
		return getStr("ELEC_ID");
	}

	public void setGasId(java.lang.String gasId) {
		set("GAS_ID", gasId);
	}
	
	public java.lang.String getGasId() {
		return getStr("GAS_ID");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

}
