package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmsReport<M extends BaseEmsReport<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setUID(java.lang.String UID) {
		set("UID", UID);
	}
	
	public java.lang.String getUID() {
		return getStr("UID");
	}

	public void setReportName(java.lang.String reportName) {
		set("REPORT_NAME", reportName);
	}
	
	public java.lang.String getReportName() {
		return getStr("REPORT_NAME");
	}

	public void setReportCode(java.lang.String reportCode) {
		set("REPORT_CODE", reportCode);
	}
	
	public java.lang.String getReportCode() {
		return getStr("REPORT_CODE");
	}

	public void setReportType(java.lang.String reportType) {
		set("REPORT_TYPE", reportType);
	}
	
	public java.lang.String getReportType() {
		return getStr("REPORT_TYPE");
	}

	public void setReportPath(java.lang.String reportPath) {
		set("REPORT_PATH", reportPath);
	}
	
	public java.lang.String getReportPath() {
		return getStr("REPORT_PATH");
	}

	public void setREMARK(java.lang.String REMARK) {
		set("REMARK", REMARK);
	}
	
	public java.lang.String getREMARK() {
		return getStr("REMARK");
	}

}
