package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmsAccount<M extends BaseEmsAccount<M>> extends Model<M> implements IBean {

	public void setAccountCode(java.lang.String accountCode) {
		set("accountCode", accountCode);
	}
	
	public java.lang.String getAccountCode() {
		return getStr("accountCode");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	public void setUnitId(java.lang.Integer unitId) {
		set("unitId", unitId);
	}
	
	public java.lang.Integer getUnitId() {
		return getInt("unitId");
	}

}
