package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlDevicesCurrent<M extends BaseXlDevicesCurrent<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDid(java.lang.Integer did) {
		set("did", did);
	}
	
	public java.lang.Integer getDid() {
		return getInt("did");
	}

	public void setDaycurrent(java.lang.Float daycurrent) {
		set("daycurrent", daycurrent);
	}
	
	public java.lang.Float getDaycurrent() {
		return getFloat("daycurrent");
	}

	public void setMonthcurrent(java.lang.Float monthcurrent) {
		set("monthcurrent", monthcurrent);
	}
	
	public java.lang.Float getMonthcurrent() {
		return getFloat("monthcurrent");
	}

	public void setCurrent(java.lang.Float current) {
		set("current", current);
	}
	
	public java.lang.Float getCurrent() {
		return getFloat("current");
	}

	public void setLastupdatetime(java.util.Date lastupdatetime) {
		set("lastupdatetime", lastupdatetime);
	}
	
	public java.util.Date getLastupdatetime() {
		return get("lastupdatetime");
	}

}
