package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlUnitsDevices<M extends BaseXlUnitsDevices<M>> extends Model<M> implements IBean {


	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}


	public void setIoo(java.lang.String ioo) {
		set("ioo", ioo);
	}

	public java.lang.String getIoo() {
		return getStr("ioo");
	}


	public void setGroupName(java.lang.String groupname) {
		set("groupname", groupname);
	}

	public java.lang.String getGroupName() {
		return getStr("groupname");
	}


	public void setGroupId(java.lang.String groupid) { set("groupid", groupid); }

	public java.lang.String getGroupId() { return getStr("groupid"); }


	public void setDataId(java.lang.String dataid) { set("dataid", dataid); }

	public java.lang.String getsetDataId() { return getStr("dataid"); }


	public void setAnalogId(java.lang.String analogid) { set("analogid", analogid); }

	public java.lang.String getAnalogId() { return getStr("analogid"); }


	public void setDid(java.lang.String did) { set("did", did); }

	public java.lang.String getDid() { return getStr("did"); }

	public void setName(java.lang.String name) { set("name", name); }

	public java.lang.String getName() { return getStr("name"); }

	public void setUserid(java.lang.String userid) { set("userid", userid); }

	public java.lang.String getUserid() { return getStr("userid"); }


}
