package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEerCoal<M extends BaseEerCoal<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDtype(java.lang.String dtype) {
		set("dtype", dtype);
	}
	
	public java.lang.String getDtype() {
		return getStr("dtype");
	}

	public void setRadio(java.lang.String radio) {
		set("radio", radio);
	}
	
	public java.lang.String getRadio() {
		return getStr("radio");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

}
