package com.ems.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseXlUnitlink<M extends BaseXlUnitlink<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setUt(java.lang.String ut) {
		set("ut", ut);
	}
	
	public java.lang.String getUt() {
		return getStr("ut");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setParentunitid(java.lang.Integer parentunitid) {
		set("parentunitid", parentunitid);
	}
	
	public java.lang.Integer getParentunitid() {
		return getInt("parentunitid");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	public void setDataid(java.lang.Integer dataid) {
		set("dataid", dataid);
	}
	
	public java.lang.Integer getDataid() {
		return getInt("dataid");
	}

	public void setIo(java.lang.Integer io) {
		set("io", io);
	}
	
	public java.lang.Integer getIo() {
		return getInt("io");
	}

}
