package com.ems.common.model;

import com.ems.common.model.base.BaseCthyDevicesInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CthyDevicesInfo extends BaseCthyDevicesInfo<CthyDevicesInfo> {
	
}
