package com.ems.common.model;

import com.ems.common.model.base.BaseEerTubenet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EerTubenet extends BaseEerTubenet<EerTubenet> {
	
}
