package com.ems.common.model;

import com.ems.common.model.base.BaseEerUserinfoTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EerUserinfoTemp extends BaseEerUserinfoTemp<EerUserinfoTemp> {

}
