package com.ems.common.model;

import com.ems.common.model.base.BaseEmsAccountExtend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsAccountExtend extends BaseEmsAccountExtend<EmsAccountExtend> {
	
}
