package com.ems.common.model;

import com.ems.common.model.base.BaseEmsAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsAccount extends BaseEmsAccount<EmsAccount> {
	
}
