package com.ems.common.model;

import com.ems.common.model.base.BaseEmsCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsCompany extends BaseEmsCompany<EmsCompany> {
	
}
