package com.ems.common.model;

import com.ems.common.model.base.BaseEmsDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsDevice extends BaseEmsDevice<EmsDevice> {
	
}
