package com.ems.common.model;

import com.ems.common.model.base.BaseEmsElecgasGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsElecgasGroup extends BaseEmsElecgasGroup<EmsElecgasGroup> {
	
}
