package com.ems.common.model;

import com.ems.common.model.base.BaseEmsReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsReport extends BaseEmsReport<EmsReport> {
	
}
