package com.ems.common.model;

import com.ems.common.model.base.BaseEmsTaskconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsTaskconfig extends BaseEmsTaskconfig<EmsTaskconfig> {
	
}
