package com.ems.common.model;

import com.ems.common.model.base.BaseEmsUnitcalcgroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmsUnitcalcgroup extends BaseEmsUnitcalcgroup<EmsUnitcalcgroup> {
	
}
