package com.ems.common.model;

import com.ems.common.model.base.BaseUsertoken;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usertoken extends BaseUsertoken<Usertoken> {

}
