package com.ems.common.model;

import com.ems.common.model.base.BaseUserinfo;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userinfo extends BaseUserinfo<Userinfo> {

    public void UpdateToken(String userid,String token){

        Db.update("update userinfo set token='"+token+"' where userid="+userid);

    }

    public Userinfo  getUserinfoByToken(String token){

         return  findFirst("select* from usertoken where token ='"+token+"'");

    }

    public Userinfo  getUserByToken(String token){

        return  findFirst("select* from userinfo where token ='"+token+"'");

    }

}
