package com.ems.common.model;

import com.ems.common.model.base.BaseUsersetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usersetting extends BaseUsersetting<Usersetting> {
	
}
