package com.ems.common.model;

import com.ems.common.model.base.BaseWarningSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarningSetting extends BaseWarningSetting<WarningSetting> {
	
}
