package com.ems.common.model;

import com.ems.common.model.base.BaseWarningInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarningInfo extends BaseWarningInfo<WarningInfo> {
	
}
