package com.ems.common.model;

import com.ems.common.model.base.BaseWarterMeterInput;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarterMeterInput extends BaseWarterMeterInput<WarterMeterInput> {
	
}
