package com.ems.common.model;

import com.ems.common.model.base.BaseXlAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlAccount extends BaseXlAccount<XlAccount> {
	
}
