package com.ems.common.model;

import com.ems.common.model.base.BaseXlAnalogdoc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlAnalogdoc extends BaseXlAnalogdoc<XlAnalogdoc> {
	
}
