package com.ems.common.model;

import com.ems.common.model.base.BaseXlAnalogTransfer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlAnalogTransfer extends BaseXlAnalogTransfer<XlAnalogTransfer> {
	
}
