package com.ems.common.model;

import com.ems.common.model.base.BaseXlDatacode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDatacode extends BaseXlDatacode<XlDatacode> {
	
}
