package com.ems.common.model;

import com.ems.common.model.base.BaseXlDaydataE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDaydataE extends BaseXlDaydataE<XlDaydataE> {
	
}
