package com.ems.common.model;

import com.ems.common.model.base.BaseXlDaydata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDaydata extends BaseXlDaydata<XlDaydata> {
	
}
