package com.ems.common.model;

import com.ems.common.model.base.BaseXlDevices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDevices extends BaseXlDevices<XlDevices> {
	
}
