package com.ems.common.model;

import com.ems.common.model.base.BaseXlDevicesCurrent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDevicesCurrent extends BaseXlDevicesCurrent<XlDevicesCurrent> {
	
}
