package com.ems.common.model;

import com.ems.common.model.base.BaseXlDevicesE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlDevicesE extends BaseXlDevicesE<XlDevicesE> {
	
}
