package com.ems.common.model;

import com.ems.common.model.base.BaseXlElectric;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlElectric extends BaseXlElectric<XlElectric> {
	
}
