package com.ems.common.model;

import com.ems.common.model.base.BaseXlGroupanalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlGroupanalog extends BaseXlGroupanalog<XlGroupanalog> {
	
}
