package com.ems.common.model;

import com.ems.common.model.base.BaseXlMonthdata;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlMonthdata extends BaseXlMonthdata<XlMonthdata> {
	
}
