package com.ems.common.model;

import com.ems.common.model.base.BaseXlUnitsDevices;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlUnitsDevices extends BaseXlUnitsDevices<XlUnitsDevices> {
	
}
