package com.ems.common.model;

import com.ems.common.model.base.BaseXlUnitcalcgroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlUnitcalcgroup extends BaseXlUnitcalcgroup<XlUnitcalcgroup> {
	
}
