package com.ems.common.model;

import com.ems.common.model.base.BaseXlUnitlinkE;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlUnitlinkE extends BaseXlUnitlinkE<XlUnitlinkE> {
	
}
