package com.ems.common.model;

import com.ems.common.model.base.BaseXlUnitlink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlUnitlink extends BaseXlUnitlink<XlUnitlink> {
	
}
