package com.ems.common.model;

import com.ems.common.model.base.BaseXlZhztUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlZhztUser extends BaseXlZhztUser<XlZhztUser> {
	
}
