package com.ems.common.model;

import com.ems.common.model.base.BaseXlZhztWarter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlZhztWarter extends BaseXlZhztWarter<XlZhztWarter> {
	
}
