package com.ems.common.model;

import com.ems.common.model.base.BaseXlZhztCounter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class XlZhztCounter extends BaseXlZhztCounter<XlZhztCounter> {
	
}
