package com.ems.unit;

import com.alibaba.fastjson.annotation.JSONField;
import com.ems.common.model.XlAnalogdoc;
import com.ems.common.model.base.BaseXlUnitsDevices;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Devices extends BaseXlUnitsDevices<Devices> {


    UnitService service = new UnitService();

    @JSONField(ordinal=100)
    public List<XlAnalogdoc> analogdocs;

    public void setChilds(){
        analogdocs = service.getChildAidDoc(getDid(),getUserid());
    }
}
